# Generated by Django 5.0.7 on 2024-07-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2. Course Category'},
        ),
        migrations.AddField(
            model_name='course',
            name='feature_img',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='techs',
            field=models.TextField(null=True),
        ),
    ]
