# Generated by Django 5.0.7 on 2024-08-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coursecategory_options_course_feature_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='feature_img',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
    ]
