# Generated by Django 5.0.7 on 2024-08-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_feature_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='feature_img',
            new_name='featured_img',
        ),
    ]
